id: P000321
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:54.002970
source_metadata:
  id: bdr:W3PD194
  title: ཟངས་རི་རྫོང་གི་དཀར་ཆག
  author: ''
  volumes:
    83956a5daae549248cd70a6122707bd8:
      image_group_id: I4PD4607
      title: Volume 1 of zangs ri rdzong gi dkar chag
      volume_number: 1
      total_pages: 916
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
